default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: loudthinking_development

test:
  <<: *default
  database: loudthinking_test

production:
  <<: *default
  database: loudthinking_production